Create the `bookcatalogue` microservice:

`mn create-app --lang groovy example.micronaut.bookcatalogue.bookcatalogue`

The previous command creates a folder named `bookcatalogue` and a Micronaut app inside it with
default package: `example.micronaut.bookcatalogue`.

[source,groovy]
.bookcatalogue/src/main/groovy/example/micronaut/bookcatalogue/BooksController.groovy
----
include::{sourceDir}/bookcatalogue/src/main/groovy/example/micronaut/bookcatalogue/BooksController.groovy[]
----

<1> The class is defined as a controller with the http://docs.micronaut.io/latest/api/io/micronaut/http/annotation/Controller.html[@Controller] annotation mapped to the path `/books`
<2> The `@Get` annotation is used to map the index method to `/books` requests that use an HTTP GET.

The previous controller responds a `Flowable<Book>`. Create the `Book` POJO:

[source,groovy]
.bookcatalogue/src/main/groovy/example/micronaut/bookcatalogue/Book.groovy
----
include::{sourceDir}/bookcatalogue/src/main/groovy/example/micronaut/bookcatalogue/Book.groovy[]
----

Write a test:

[source,groovy]
.bookcatalogue/src/test/groovy/example/micronaut/bookcatalogue/BooksControllerSpec.groovy
----
include::{sourceDir}/bookcatalogue/src/test/groovy/example/micronaut/bookcatalogue/BooksControllerSpec.groovy[]
----

<1> Annotate the class with `@MicronautTest` to let Micronaut starts the embedded server and inject the beans. More info: https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html[https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html].
<2> Inject the `HttpClient` bean in the application context.
<3> It is easy to create HTTP requests with a fluid API.
<4> Parse easily JSON into Groovy objects.

Edit `application.yml`

[source,yaml]
.bookcatalogue/src/main/resources/application.yml
----
include::{sourceDir}/bookcatalogue/src/main/resources/application.yml[tag=mn]
----

<1> Configure the application name. The app name will be use by the discovery service.
<2> Configure the app to listen at port 8081

Create a file named `application-test.yml` which is used in the test environment:

[source,yaml]
.bookcatalogue/src/main/resources/application-test.yml
----
include::{sourceDir}/bookcatalogue/src/main/resources/application-test.yml[tag=port]
----

<1> Start the micronaut microservice at a random port when running the tests.